paths:
  uploads: uploads
  static: ''
  collections: 
  collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data: ''
  layouts:
collections_config: {}
_inputs: {}
_select_data: {}
_structures: {}
_editables:
  content:
    bold: true
    italic: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    undo: true
    redo: true

timezone: Etc/UTC
